create database hotelmanagementsystem;
show databases;
use hotelmanagementsystem;
create table login(username varchar(25), password varchar(25));
insert into login values('admin' ,'12345');
 create table employee(name varchar(25) , age varchar(15), gender varchar(15), job varchar(30),  salary varchar(30), phone varchar(15), email varchar(40), aadhar varchar(20));
 create table room(roomnumber varchar(10), availability varchar(20),cleaning_status varchar(20), price varchar(20), bed_type varchar(20) );
 create table driver(name varchar(10), age varchar(20),gender varchar(20), company varchar(20), model varchar(50), available varchar(20), location varchar(100));
 create table customer(id varchar(10), num varchar(30), name varchar(30), gender varchar(20), country varchar(20), room varchar(50), CheckInTime varchar(40),  deposit varchar(100));
 insert into department values('Front office','500000');
 insert into department values('HouseKeeping','40000');
 insert into department values('Food and Beverages','23000');
 insert into department values('Kitchen and Food Production','54000');
 insert into department values('Security','32000');
 select * from login;
 select * from room;
 select * from department;
 select * from employee;
 select * from customer;
 select * from driver;
 update customer set deposit = 500;
 delete from driver;
 set sql_safe_updates = 0;